# fly.toml app configuration file generated for lina-insta-clone on 2024-01-13T12:03:01+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lina-insta-clone"
primary_region = "nrt"
console_command = "/rails/bin/rails console"

[build]

[processes]
  app = "./bin/rails server"
  sidekiq = "bundle exec sidekiq"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
